package entity;

public enum Specialization {
    CARDIOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    DERMATOLOGY,
    PSYCHIATRY,
    ONCOLOGY,
    GENERAL_SURGERY,
    INTERNAL_MEDICINE,
    OBSTETRICS_GYNECOLOGY,
    OPHTHALMOLOGY,
    OTOLARYNGOLOGY,
    RADIOLOGY,
    PATHOLOGY,
    FAMILY_MEDICINE,
    EMERGENCY_MEDICINE
}
